name: MastodonLink
version: '${version}'
main: com.connorcode.mastodonlink.MastodonLink
api-version: 1.19
load: STARTUP
authors: [ ConnorSlade ]
website: https://connorcode.com

commands:
  mastodon:
    usage: /mastodon <playername>
    description: Gets another player's Mastodon account